name: soloWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: linux30.unoeuro.com
          username: markosdesign.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/
          server-dir: /public_html/eisner-2025-todo-TS-app-bde-main/
          timeout: 60000

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests/*"

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist/

  deploy:
    needs: integration-delivery
    runs-on: ubuntu-22.04
    environment: Live
    steps:
      - name: Load build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist/

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: linux30.unoeuro.com
          username: markosdesign.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/live/
          server-dir: /public_html/eisner-2025-todo-TS-app-bde-main/
          timeout: 60000